src/Helsenorge.Messaging/Helsenorge.Messaging.nuspec, src/Helsenorge.Messaging/MessagingClient.cs
Lagt til liten fiks så timereservasjon går igjennom selv om sender ikke har CPP for dette
=> Timereservasjon without cpp

GlobalAssemblyInfo.cs, src/Helsenorge.Messaging/Helsenorge.Messaging.nuspec
Update version and removed beta prefix
=> Removed beta prefix of nuget package and set version number of assembly

GlobalAssemblyInfo.cs, src/Helsenorge.Registries/Utilities/CacheExtensions.cs
Changed get cache call from Async to Sync as Async has stopped working and does not return anything for Helsenorge platform
=> Changed get cache call from Async to Sync

GlobalAssemblyInfo.cs, src/Helsenorge.Messaging/Abstractions/IncomingMessage.cs, src/Helsenorge.Messaging/Http/HttpServiceBusReceiver.cs, src/Helsenorge.Messaging/Http/HttpServiceBusSender.cs, src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
Also: HTTP/AMQP implementation sets custom HTTP request header
=> IncomingMessage: Property for message signed status

src/Helsenorge.Messaging/Abstractions/IMessagingMessage.cs, src/Helsenorge.Messaging/Http/IncomingHttpMessage.cs, src/Helsenorge.Messaging/Http/OutgoingHttpMessage.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs, test/Helsenorge.Messaging.Tests/Mocks/MockMessage.cs
* Added argument payload to IMessagingMessage.Clone to be able to decide
if the payload should be included or not included when cloning the message
* Default value of payload argument is true
=> Added argument to Clone to include or not include payload

src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs
Added check for missmatch between her id sent to and received from for
sync messaged. Added logging as critical when this happends.
=> Sync Message: Better logging of mismatching HER-id

src/Helsenorge.Messaging/Helsenorge.Messaging.nuspec, src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs
Fixed an issue in the code that waits for responds on a reply message.
The issue arised when it got respond respond from another message then
the one it was currently processing.
=> Fixed issue causing logging of missmatch HerId

src/Helsenorge.Messaging/MessagingSettings.cs
Allow users of the library not to configure synchronous task
=> Allow Synchronous ProcessingTask to be zero

src/Helsenorge.Messaging/Abstractions/IMessagingMessage.cs, src/Helsenorge.Messaging/Abstractions/IncomingMessage.cs, src/Helsenorge.Messaging/Helsenorge.Messaging.csproj, src/Helsenorge.Messaging/Http/IncomingHttpMessage.cs, src/Helsenorge.Messaging/Http/OutgoingHttpMessage.cs, src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs, src/Helsenorge.Registries/Helsenorge.Registries.csproj, test/Helsenorge.Messaging.Tests/Mocks/MockMessage.cs
* Expose DeliveryCount property on interface and implementations.
* Bumped version number to 3.0.4-beta05
=> Expose DeliveryCount property on interfaces

src/Helsenorge.Messaging/Abstractions/IMessageProtection.cs, src/Helsenorge.Messaging/Abstractions/MessageProtection.cs, src/Helsenorge.Messaging/Security/NoMessageProtection.cs, src/Helsenorge.Messaging/Security/SignThenEncryptMessageProtection.cs, src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, test/Helsenorge.Messaging.Tests/BaseTest.cs, test/Helsenorge.Messaging.Tests/Mocks/MockMessageProtection.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Senders/AsynchronousSendTests.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Senders/SynchronousSendTests.cs
* Had previously removed the local certification validation, did some
refactoring and added it back
* issue #46
=> fix: re-add local certificate validation

Documentation/Feilkoder.md, src/Helsenorge.Messaging/Abstractions/MessagingEntityCache.cs, src/Helsenorge.Messaging/Abstractions/MessagingException.cs, src/Helsenorge.Messaging/Helsenorge.Messaging.csproj, src/Helsenorge.Messaging/ServiceBus/Receivers/AsynchronousMessageListener.cs, src/Helsenorge.Messaging/ServiceBus/Receivers/ErrorMessageListener.cs, src/Helsenorge.Messaging/ServiceBus/Receivers/SynchronousMessageListener.cs, src/Helsenorge.Messaging/ServiceBus/Receivers/SynchronousReplyListener.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusLoggingExtensions.cs, src/Helsenorge.Registries/Helsenorge.Registries.csproj
* Add more informational logging
* issue #79
=> enh: Enhance/more logging

src/Helsenorge.Messaging/Helsenorge.Messaging.csproj, src/Helsenorge.Registries/Abstractions/CommunicationPartyDetails.cs, src/Helsenorge.Registries/AddressRegistry.cs, src/Helsenorge.Registries/Helsenorge.Registries.csproj
=> Added parentage fields to CommunicationPartyDetails

src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusLoggingExtensions.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Senders/SynchronousSendTests.cs
**Endringer**
- Oppdatert test Send_Synchronous_Timeout.
- Laget ny logg extension LogTimeoutError.
=> Forbedring logging av synkrone meldinger med timeout

Directory.build.props, src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusLoggingExtensions.cs
Added MessageFunction to the logging of timeout of sync messages.
=> Added MessageFunction to the logging of timed out sync messages

src/Helsenorge.Messaging.Client/Program.cs, src/Helsenorge.Messaging.Server/Program.cs, src/Helsenorge.Messaging/Abstractions/IMessagingClient.cs, src/Helsenorge.Messaging/MessagingClient.cs, src/Helsenorge.Messaging/MessagingServer.cs, test/Helsenorge.Messaging.Tests/BaseTest.cs, test/Helsenorge.Messaging.Tests/OptionTests.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs
Marked the old ctor as obsolete and updated the tests to use new ctor.
=> Removed the ILogger from the constructor

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
=> fix: NullReference in ReportErrorOnLocalCertificate

Directory.build.props, src/Helsenorge.Messaging/ServiceBus/ServiceBusHttpClient.cs
Fixed a error in a debug log statement that ran when trying to renew the
peek lock of message on the queue
=> Fixed error in logging when renewing lock

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Senders/AsynchronousSendTests.cs
Added the Certificate Error to both logging and Exception that is thrown. This will make it easier to figure out what is the problem with the Certificate.
=> Added Certificate Error to logging and exception

src/Helsenorge.Messaging/ServiceBus/CachedAmpqSessionEntity.cs
Tillatter kun en samtidig som sjekker at connection er åpen
=> Trådsikrer EnsureOpen i CachedAmpqSessionEntity

src/Helsenorge.Messaging/MessagingSettings.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusConnection.cs
* Expose the properties MaxSessionPerConnection and MaxLinksPerSession
from AMQPNetLite's:
- ConnectionFactory.AMQP.MaxSessionPerConnection
- ConnectionFactory.AMQP.MaxLinksPerSession
=> feat: MaxSessionsPerConnection and MaxLinksPerSession

src/Helsenorge.Registries/CollaborationProtocolRegistry.cs, test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs, test/Helsenorge.Registries.Tests/Files/CPA_v2_51795e2c-9d39-44e0-9168-5bee38f20819.xml
Added support for new CPPA service. Fixed issue with mapping of message parts where it did not get mapped propertly with new version.
=> Support for new CPPA service

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/ErrorReceiveTests.cs
Fixed an issue where properties where not set on Error messages when returning the error message to sender.
=> Fixed issue with properties on Error message

src/Helsenorge.Messaging/ServiceBus/ServiceBusReceiver.cs
Not intializing the methods Complete, Reject, Release, Deadletter,
RenewLock and Modify
Should have been part of commit: 4a13209f
=> fix: Not initializing Complete, Deadletter methods

src/Helsenorge.Messaging/Abstractions/MessagingEntityCache.cs
This adds more logging entries so that we have better control over ActiveCount for cached entities. And also includes how many entries there are in our cache when trimming cache
=> MessagingEntityCache: Add Logging to visualize ActiveCount + cached EntryCount

src/Helsenorge.Messaging/Abstractions/MessagingEntityCache.cs
This patch fixes situations when our client gets disconnected from the
message broker and would end up in an unsynchronized state trying to
reuse entities that were closed.
=> MessageEntityCache: Do not reuse closed entities

Documentation/Konfigurasjon.md
Endret connectionstring under Versjon 4.x og nyere til amqps://:@sb.nhn.no:5671/NHNPRODServiceBus
fra amqps://:@sb.nhn.no:5671/NHNTestServiceBus
=> Update production connectionstring Konfigurasjon.md

src/Helsenorge.Messaging/ServiceBus/ServiceBusConnection.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusHttpClient.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusReceiver.cs, test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusMessageTests.cs
throwing exception if they are used with RabbitMQ
=> deprecating RenewTimeout and DeadLetter

.github/workflows/build.yml, .github/workflows/nuget-deploy.yml, src/Helsenorge.Messaging/Helsenorge.Messaging.csproj, src/Helsenorge.Registries/Helsenorge.Registries.csproj, src/Helsenorge.Registries/Utilities/CacheExtensions.cs, test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj, test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj
=> deps: Add net6.0 Target

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusLoggingExtensions.cs, test/Helsenorge.Messaging.Tests/ServiceBus/Senders/SynchronousSendTests.cs
When troubleshooting it is essential to be able to locate at which point in our code something might stall.
=> ServiceBus: Log the response time for certifcate validation

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, src/Helsenorge.Messaging/ServiceBus/ServiceBusLoggingExtensions.cs
This adds support for logging hostname and path on start of receive and send operations, in addition on generic service bus exceptions in our receiver/listener.
=> ServiceBus: Enchance logging by logging hostname and path

src/Helsenorge.Messaging/MessagingSettings.cs, test/Helsenorge.Messaging.Tests/OptionTests.cs
Do not run the validation routine if ProcessingTasks == 0.
=> Settings: Let the user decide if it want async, sync or error queues

src/Helsenorge.Registries/AddressRegistry.cs
This is an attempt to minify code duplication.
=> First pass of refactoring AddressRegistry abstraction

src/Helsenorge.Messaging/Security/SignThenEncryptMessageProtection.cs
Adds an opt-in ability to control the `IncludeOption` parameter of `CmsSigner` when signing messages.
The default value of this option is `ExcludeRoot`, which causes the framework to enumerate the certificate chain using the computer's certificate store. This causes problems if the intermediate certificates aren't installed, in some cases creating a considerable delay for each message being signed. In most cases though, the recipient will only need the end (signing) certificate in order to compare against an expected certificate, in which case `EndCertOnly` can be safely used.
=> Messaging: Ability to control certs embedded in signature

src/Helsenorge.Registries/Abstractions/CollaborationProtocolMessage.cs, src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs, src/Helsenorge.Registries/CollaborationProtocolRegistry.cs, test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs
This reverts commit 0c329eccc509e43e2e3059b6d978ebb8ded2a5eb.
=> Revert "Registries: Mapping changes for abstractions"

src/Helsenorge.Registries/CollaborationProtocolRegistry.cs, src/Helsenorge.Registries/ServiceBusEvents.cs
Add XML comments to avoid getting spammed with warnings in our diff and build actions.
=> Registries: Add XML Comments to public members

Documentation/Feilkoder.md, src/Helsenorge.Messaging/Abstractions/MessagingException.cs, src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs, src/Helsenorge.Registries/AddressRegistry.cs, src/Helsenorge.Registries/InvalidHerIdException.cs
This is meant to log and remove messages where the HerId isnt valid
=> Fix handling of invalid HerIDs from AR

src/Helsenorge.Messaging/MessagingCore.cs, src/Helsenorge.Messaging/MessagingEncryptionType.cs, src/Helsenorge.Messaging/MessagingSettings.cs, src/Helsenorge.Messaging/Security/SignThenEncryptMessageProtection.cs
Due to production issues with AES256, are we adding a setting to allow for swapping between the two encryption types
=> Add setting to swap between AES256 and 3DES encryption

src/Helsenorge.Messaging/Helsenorge.Messaging.csproj, src/Helsenorge.Registries/Helsenorge.Registries.csproj, test/Helsenorge.Messaging.IntegrationTests/Helsenorge.Messaging.IntegrationTests.csproj, test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj, test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj
This reverts commit d333a7d06a2a88289423b58fa3cc951a75f39ff9.
=> Revert "deps: Remove Target Frameworks netstandard2.0 and netcore3.1"

src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs
Revert "Revert "Registries: Make sure we null-check ProcessSpecification"
This reverts commit b638746d7b493933f14293e138fbc5ca4175e41d.
=> Revert "Revert "Registries: Make sure we null-check ProcessSpecification"

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs, test/Helsenorge.Messaging.Tests/Security/SignThenEncryptMessageProtectionTests.cs
Removed ' from LogStartSend. 
LogStartReceive and LogStartSend now logs the same Additional Data
=> Update logging in LogStartSend.

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
These are temporarily log statements to let us verify the AlgorithmIdentifier we use in addition to PKCS information.
=> Messaging: Log AlgorithmIdentifier and PKCS information

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
This reverts commit ff7a627d1c916ff0fe235aa7b664069a709cd2b1.
=> Revert "Messaging: Log AlgorithmIdentifier and PKCS information"

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
This reverts commit 219d3d46924f3dd2128448455128abd22491fd87.
=> Messaging: Revert temporarily use Receive instead of ReceiveAsync

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
Added start & end logging when returning message to senders error-queue
Internal NHN bug-reference: 294616
=> Added start and end logging on SendError

src/Helsenorge.Messaging/Abstractions/AmqpEntityCache.cs, src/Helsenorge.Messaging/Amqp/AmqpCore.cs, test/Helsenorge.Messaging.Tests/Amqp/BusMessageTests.cs, test/Helsenorge.Messaging.Tests/Amqp/Receivers/AsynchronousReceiveTests.cs, test/Helsenorge.Messaging.Tests/Amqp/Receivers/ErrorReceiveTests.cs, test/Helsenorge.Messaging.Tests/Amqp/Receivers/SynchronousReceiveTests.cs, test/Helsenorge.Messaging.Tests/BaseTest.cs, test/Helsenorge.Messaging.Tests/MessagingEntityCacheTests.cs
=> Everywhere: Use UTC time everywhere

src/Helsenorge.Messaging/Amqp/AmqpCore.cs, src/Helsenorge.Messaging/Amqp/Receivers/QueueAddressNullOrEmptyStringException.cs
Used to log out the herId causing the exception
=> Created new QueueAddressNullOrEmptyStringException.

Directory.build.props
5.0.4 build failed due to user issue
=> Bump version to 5.0.5

Directory.build.props, src/Helsenorge.Messaging/Amqp/AmqpCore.cs, src/Helsenorge.Messaging/Amqp/MetadataHelper.cs
made the code fetchign namespace more robust
adding a fallback if normal method return emtpy string
=> fixed bug when fetching namespace from apprec created in helsenorge internal

Directory.build.props, src/Helsenorge.Messaging/MessagingCore.cs, src/Helsenorge.Registries/CertificateValidator.cs, src/Helsenorge.Registries/CollaborationProtocolRegistry.cs, test/Helsenorge.Registries.Tests/CertificateValidatorTests.cs
- Added logging of status and information when we get revoked cerificate from certificate validation
- Added logging when we retrive profile from CPA, CPP or Cache to determind where the source of the certificate comes from
=> Added logging of revoked Certificate and source of the certificate

Documentation/MigrateFromSoapToRest.md
- Rename MigrateFrom5to5-2.md to MigrateFromSoapToRest.md
- Updated text in MigrateFromSoapToRest.md
=> Update and rename Migrate guide

.github/dependabot.yml, test/Helsenorge.Messaging.AdminLib.Tests/Helsenorge.Messaging.AdminLib.Tests.csproj, test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj, test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj
Also remove the ignore section in dependabot configuration for major versions.
=> deps: Update various dependencies
