src/Helsenorge.Messaging/MessagingClient.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/SynchronousReplyListener.cs
src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Senders/SynchronousSendTests.cs

Fixes #6.
Added hooks for handling incoming synchronous reply messages. As discussed, we could potentially split the IMessagingNotification interface as a first refactoring step, and reduce the number of empty methods in SynchronousSender.

Error handling for synchronous reply messages

---

src/Helsenorge.Registries/Abstractions/IAddressRegistry.cs
src/Helsenorge.Registries/Abstractions/ICollaborationProtocolRegistry.cs
src/Helsenorge.Registries/AddressRegistry.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs

Enables us to force cache refresh, which we do on an interval. This
helps us maintain a low response time and avoid calls to AR being done
on a sync call. 
This replaces #14 .

Forced Cache Update

---

src/Helsenorge.Registries/AddressRegistry.cs

Fixed mapping of Name from AR, if displayname is empty (as it often is) then we use the name instead

Fixed mapping of Name from AR

---

GlobalAssemblyInfo.cs
src/Helsenorge.Messaging/Helsenorge.Messaging.nuspec
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Registries/AddressRegistry.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
src/Helsenorge.Registries/Utilities/CacheExtensions.cs

Change call to SetAsync on IDistributedCache to be fire and forget because of thread locking errors and to improve performance of framework

Fix thread sync problems when hosted in ASP.NET

---

src/Helsenorge.Registries/Abstractions/CertificateErrors.cs

Issue #27 Enum flags with invalid(?) values

Fix: CertificateErrors enum conforms to how bit flags should be defined

---

src/Helsenorge.Messaging/Abstractions/IMessagingMessage.cs
src/Helsenorge.Messaging/Http/IncomingHttpMessage.cs
src/Helsenorge.Messaging/Http/OutgoingHttpMessage.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
test/Helsenorge.Messaging.Tests/Mocks/MockFactory.cs
test/Helsenorge.Messaging.Tests/Mocks/MockMessage.cs
test/Helsenorge.Messaging.Tests/Mocks/MockSender.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/SynchronousReceiveTests.cs

When replying to a synchronous message, currently if the message cannot be sent because of an invalid replyto queue it is retried 10 times and then sent to the deadletter queue. 
Retrying sending is not useful for a synchronous message that will timeout before it can be retried. Resending will also not work since the queue is likely not there later. Instead we send the message to the error queue of the sender to inform of the error with an error message transport:invalid-field-value.
Also added support for sending a message to the deadletter queue immediately. This is currently unused.

Send message with invalid replyto queue to error queue

---

src/Helsenorge.Messaging/Security/SignThenEncryptMessageProtection.cs

Error handling in parsing stream to XDocument had become different in the class for encrypted and the class for unencrypted messages. The unit test for parsing errors used the class for unencrypted messages and is correct for invalid xml messages. 
This change reuses to code for unencrypted messages to ensure consistency and ensure proper error handling for encrypted messages

Parsing stream to XDocument error handling inconsistent

---

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs

Remote encryption certificate error currently provides no information about which certificate has caused the fault. Include the serial number of the certificate and HerId to help troubleshooting.

Improve error message for invalid remote encryption certificate

---

src/Helsenorge.Messaging/Abstractions/IMessagingNotification.cs
src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Messaging/MessagingServer.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/ErrorMessageListener.cs
src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/ErrorReceiveTests.cs

There is no NotifyErrorMessageReceivedStarting method called during message processing. This has resulted in difficulties for clients setting a correlation for a request and so made managing the error queue problematic.

Legg til NotifyErrorMessageReceivedStarting method

---

src/Helsenorge.Messaging/MessagingSettings.cs

* Revert setting of SynchronousSettings.ProcessingTasks to zero in
3904c373
* Parties that want to override the default would have to set this to
zero manually

Default SynchronousSettings.ProcessingTasks to 2

---

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/ErrorReceiveTests.cs

Error messages will not be decrypted, so CPA information isn't needed.
CPA information is only needed for the decryption.

Removed CPA lookup when retriving error messages

---

src/Helsenorge.Registries/Abstractions/CollaborationProtocolRole.cs
src/Helsenorge.Registries/Abstractions/ProcessSpecification.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs

When mapping Collaboration Protocols from XML, the Name attribute of ProcessSpecification was not included whereas the version was. With recent improvements in the setup of Collaboration Protocols in the Address Register, this has meant an important field is missing. To highlight the changes, the 3 old fields Name, Version and VersionString are marked as obsolete. A new object is available for the ProcessSpecification and a new property is available for the Name attribute of the Role, RoleName

Add ProcessSpecification to CollaborationProtocolRole

---

src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs
test/Helsenorge.Registries.Tests/Files/CPP_93238.xml

Methods FindMessageForSender and FindMessageForReceiver failed for the new CPP format resulting in being unable to send messages setup using the new CPP format. Amended these methods to use the ProcessSpecification Name to be able to find the correct CollaborationProtocolMessage.

Update Registry methods for new CPP format

---

src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs

AppRec messages are not getting sent because they do not have a ProcessSpecification so the CollaborationProtocolProfile (CPP) needs to be found using a different method. This reverts to the old method of finding the CPP if it cannot be found using the ProcessSpecification.

Add Fallback for FindMessageForSender

---

src/Helsenorge.Messaging/Abstractions/ICertificateStore.cs
src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Messaging/MessagingClient.cs
src/Helsenorge.Messaging/MessagingCore.cs
src/Helsenorge.Messaging/MessagingServer.cs
src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Messaging/Security/WindowsCertificateStore.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Messaging.Tests/BaseTest.cs
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj
test/Helsenorge.Messaging.Tests/Mocks/MockCertificateStore.cs
test/Helsenorge.Messaging.Tests/OptionTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs
test/Helsenorge.Messaging.Tests/WindowsCertificateStoreTests.cs
test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj

* An interface, ICertifcateStore, so that a client can override the
default Certification Store which is Windows Certificate Store.
* If ICertificateStore is not set by the client the library will default
to Widows Certificate Store.
* #46

feature: ICertificateStore abstraction

---

src/Helsenorge.Messaging.Client/Program.cs
src/Helsenorge.Messaging/Abstractions/ICertificateStore.cs
src/Helsenorge.Messaging/Abstractions/IMessagingFactory.cs
src/Helsenorge.Messaging/Abstractions/IncomingMessage.cs
src/Helsenorge.Messaging/Abstractions/MessageProtection.cs
src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Messaging/MessagingClient.cs
src/Helsenorge.Messaging/MessagingCore.cs
src/Helsenorge.Messaging/MessagingServer.cs
src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Messaging/Security/NoMessageProtection.cs
src/Helsenorge.Messaging/Security/SignThenEncryptMessageProtection.cs
src/Helsenorge.Messaging/Security/WindowsCertificateStore.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Messaging/StreamExtensions.cs
src/Helsenorge.Messaging/XDocumentExtensions.cs
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Messaging.Tests/BaseTest.cs
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj
test/Helsenorge.Messaging.Tests/Mocks/MockCertificateStore.cs
test/Helsenorge.Messaging.Tests/Mocks/TestCertificates.cs
test/Helsenorge.Messaging.Tests/OptionTests.cs
test/Helsenorge.Messaging.Tests/Security/SignThenEncryptMessageProtectionTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Senders/AsynchronousSendTests.cs
test/Helsenorge.Messaging.Tests/WindowsCertificateStoreTests.cs
test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj

* Making necessary adjustments to the library to make use of pluggable
architecture for certificate validation, encryption and signing.
* Added abstract class MessageProtection for convenience when creating
a custom implementation of IMessageProtection
* Making some minor preparations for moving to a future scenario where
payload is a Stream rather than a XDocument as it is today.
* The bullet point above is one of the reason why I have made the old methods
Protect/Unprotect in IMessageProtection obsolete.
* The second reason is not passing in the private keys via the Protect/Unprotect 
methods, private keys certificates are now handled internally by the 
IMessageProtection implementation.
* The default implementation of IMessageProtection will retrieve the
certificates from …

feature: Pluggable architecture for encryption and signing

---

src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Registries/Helsenorge.Registries.csproj

Certificate has been obsoleted in MessagingSettings as this should no
longer be used. You can get the certificate from ICertificateStore.
It has a implementation WindowsCertificateStore that can be used.

Obsolete Certificate in MessagingSettings

---

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusLoggingExtensions.cs
test/Helsenorge.Messaging.Tests/DistributedCacheFactory.cs
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj
test/Helsenorge.Messaging.Tests/Http/TestHttpSerialization.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/SynchronousReceiveTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Senders/SynchronousSendTests.cs
test/Helsenorge.Registries.Tests/DistributedCacheFactory.cs
test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj

Lagt til LogResponseTime extensions i ServiceBusLoggingExtensions.
Oppdatert test Synchronous_Receive_OK for å se at logging gjøres. 
Se issue #79 for mer info.

Logging av responstid ved synkrone meldinger

---

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusLoggingExtensions.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Senders/SynchronousSendTests.cs

Lagt til logging av HerId, navn på kø og korrelasjon Id ved prosesserte meldinger. 
- Oppdatert test metode "Send_Synchronous_OK"
- Oppdatert logging extension LogRemoveMessageFromQueueNormal i ServiceBusLoggingExtensions
Se punkt 1 i Issue #79

Utvidet logging av synkrone meldinger

---

Directory.build.props
src/Helsenorge.Registries/Utilities/CacheExtensions.cs

Moved the method that retrives cached values to inside the try in try catch. If it fails retriving value from the cache will the application not crash and it will get new values and write new cache.

Moved getter for cache value to inside the try catch

---

Directory.build.props
src/Helsenorge.Registries/CertificateValidator.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
src/Helsenorge.Registries/X509Certificate2Extensions.cs
test/Helsenorge.Registries.Tests/CertificateValidatorTests.cs

If it's signing or encryption certificate is now determind by the keyusage information that's on the certificate. Instead of using the certId attribute in the XML.

Certification type determined by keyusage

---

Directory.build.props
src/Helsenorge.Messaging/Abstractions/IMessagingMessage.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs
test/Helsenorge.Messaging.Tests/Mocks/MockMessage.cs
test/Helsenorge.Messaging.Tests/ServiceBus/ServiceBusMessageTests.cs

There was two issues related to the implementation of AMQP.net Lite library, where how you do cloning and setting of properties has been changed.
- Cloning of message did not include payload
- Creating new properties on a message on a message through the exposed "Properties" property no longer worked
These issues has been fixed. A new method for setting the message properties has been introduced, "SetProperty" can now be used for this.

Fixed issues with cloning message and setting custom message properties

---

Directory.build.props
src/Helsenorge.Registries/Configuration/ConfigurationChannelFactory.cs
src/Helsenorge.Registries/Configuration/WcfConfiguration.cs
test/Helsenorge.Registries.Tests/Configuration/ConfigurationChannelFactoryTests.cs

Exposing the properties UseDefaultWebProxy, BypassProxyOnLocal and ProxyAddress so these can be set.

Exposing Proxy settings in WcfConfiguration file

---

Directory.build.props
src/Helsenorge.Registries/Configuration/WcfConfiguration.cs

Property for proxy had internal set which has been changed to public.
This is so they can be changed and set by config.

Exposed property for proxy so they can be set

---

src/Helsenorge.Registries/Configuration/ConfigurationChannelFactory.cs
src/Helsenorge.Registries/Configuration/WcfConfiguration.cs
test/Helsenorge.Registries.Tests/Configuration/ConfigurationChannelFactoryTests.cs

Fixed issue where the setting UseDefaultWebProxy couldn't be set to
false. Fixed by making the property mapped from config nullable so you
can detect if it was set in config or not. Made this change to the other
properties to conform with this change.

Fixed so UseDefaultWebProxy can be set to false

---

test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj

The XUnit fact tests were not running in Visual Studio for
Registries.Tests. This has been fixed by adding the
xunit.runner.visualstudio to the Helsenorge.Registries.Tests project

Added XUnit VS runner to Registries.Tests project

---

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs

* If FromHerId == 0 throw a HeaderValidationException from
ValidateMessageHeader
* This changes the behavior somewhat and is reflected in the test
Asynchronous_Receive_MissingFromHerId. We no longer get a
CertificateErrors.Missing, but now receive a HeaderValidationException
as explained above. This seems more in line with what actually is
happening.
* Since we cannot send an AppRec or Error anywhere we abort during
SendError and remove the message from queue

fix: FromHerId == 0 throw HeaderValidationException

---

src/Helsenorge.Messaging.Server/Program.cs
src/Helsenorge.Messaging/Abstractions/IMessagingServer.cs
src/Helsenorge.Messaging/MessagingServer.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/ErrorReceiveTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/SynchronousReceiveTests.cs

* BREAKING CHANGE: Async callbacks have been suffixed with Async
* There is an issue with NLog MappedDiagnosticsLogicalContext not
working in a context where async/await + ConfigureAwait(false) is
used. To get around this problem we have added sync callbacks in
addition to the async callbacks
* For more information: https://stackoverflow.com/q/39040688/1597945

refactor!: Add sync callbacks rename async callbacks

---

src/Helsenorge.Messaging/Abstractions/MessagingException.cs
src/Helsenorge.Messaging/ServiceBus/MessageReleaseThread.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs

* When an unhandled exception occurs we do not release the message and
we can therefore make our process hang for up to 10 minutes before it
gets force detached by the broker. If we have several messages in the
queue that end up with an unhandled exception we might end up in a
longer delay where we can't process messages fast enough since our
credits might be drained.
Also we do not want to release the message that threw an unhandled
exception since it will then become immediately available on the
queue.
* This commit tries to fix this by spinning up a new thread which waits
until we reach the message's LockedUntil and then releases it.

fix: Handle messages not being released properly

---

src/Helsenorge.Messaging/Abstractions/IMessagingMessage.cs
src/Helsenorge.Messaging/Abstractions/IMessagingReceiver.cs
src/Helsenorge.Messaging/Abstractions/IncomingMessage.cs
src/Helsenorge.Messaging/ServiceBus/CachedAmpqSessionEntity.cs
src/Helsenorge.Messaging/ServiceBus/DefaultTimeManager.cs
src/Helsenorge.Messaging/ServiceBus/ITimeManager.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusConnection.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusOperation.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusOperationBuilder.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusReceiver.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusSender.cs
test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusConnectionTests.cs
test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusFixture.cs
test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusMessageTests.cs
test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusReceiverTests.cs
test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusSenderTests.cs
test/Helsenorge.Messaging.Tests/Mocks/MockMessage.cs
test/Helsenorge.Messaging.Tests/Mocks/MockReceiver.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Exceptions/ServiceBusOperationTests.cs

refactor!: Add sync methods, rename async methods
BREAKING CHANGE: Add corresponding sync methods for async methods.
Rename async methods by suffixing them with Async.
refactor!: Make lambda expressions internal
BREAKING CHANGE: lambda expressions on ServiceBusMessage are now 
internal.

refactor!: Add sync methods, rename async methods

---

src/Helsenorge.Messaging/ServiceBus/ServiceBusOperation.cs

The ServiceBusOperation.Operation method did not return and ended up in
an endless loop.
Bug was introduced in 4.0.0-beta39

fix: ServiceBusOperation.Perform endless loop

---

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Senders/AsynchronousSendTests.cs
test/Helsenorge.Registries.Tests/CertificateValidatorTests.cs

This fixes changes in certificates related to the SEID2 changes.
The new certificates will no longer contain the KeyUsage flag
DataEncipherment, so instead we check for the flag KeyEncipherment.

fix: Check if KeyUsage is equal to KeyEncipherment not DataEncipherment

---

src/Helsenorge.Messaging/MessagingSettings.cs
test/Helsenorge.Messaging.Tests/OptionTests.cs

This sets the default for ErrorSettings.TimeToLive to zero. This allows
the broker to use a centralized value for how long a message is allowed
to live on error queue.

Configuration: TimeToLive default for Error Queue determined by Broker

---

src/Helsenorge.Messaging/Abstractions/MessagingEntityCache.cs
src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusFactoryPool.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusReceiverPool.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusSenderPool.cs
test/Helsenorge.Messaging.Tests/MessagingEntityCacheTests.cs

This enhances the cache by introducing several criterias for when an
entity can be recycled.
CacheEntry<T>.ClosePending is removed and we now rely on
CacheEntry<T>.ActiveCount and CacheEntry<T>.LastUsed for when an entry
is prime for recycling.
The selection process for recycling is as following:
1. MessagingEntityCache<T>.Entries > Capacity
2. Select Min(MessagingEntityCache<T>.Entries - Capacity, MaxTrimCount)
3. CacheEntry<T>.Entity.IsClosed == false
and (CacheEntry<T>.LastUsed < Now - CacheTimeToLive)
and CacheEntry<T>.ActiveCount == 0
Functional description:
1. Start recycle only if we have exceeded Capacity
2. Select min value of either
MessagingEntityCache<T>.Entries - Capacity
or MaxTrimCount
3. Entity should not be closed
and Last Time the entry was Used should be less than …

MessagingEntityCache: Introduce cache criterias for better recycling

---

src/Helsenorge.Messaging/Abstractions/MessagingEntityCache.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusFactoryPool.cs
test/Helsenorge.Messaging.Tests/MessagingEntityCacheTests.cs

The ServiceBusFactoryPool issues ServiceBusFactories which contains the
actual AMQP Connection which should not be recycled unless we shut down
or are disconnected because of network issues.
Because of this Release will never be called for a ServiceBusFactory and
ActiveCount would just be incremented forever until restart.
This commit let's us override this by setting the member variable
_incrementActiveCount of MessagingEntityCache<T> to false after creation
of the necessary ServiceBusFactories. With this change ActiveCount for a
ServiceBusFactory will never exceed ActiveCount of 1.

ServiceBusFactoryPool: Do not increment ActiveCount beyond 1

---

Documentation/Feilkoder.md
src/Helsenorge.Messaging/Abstractions/MessagingException.cs
src/Helsenorge.Messaging/MessagingServer.cs
src/Helsenorge.Registries/Abstractions/IAddressRegistry.cs
src/Helsenorge.Registries/Abstractions/ICollaborationProtocolRegistry.cs
src/Helsenorge.Registries/AddressRegistry.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
src/Helsenorge.Registries/Mocks/AddressRegistryMock.cs
src/Helsenorge.Registries/Mocks/CollaborationProtocolRegistryMock.cs
test/Helsenorge.Messaging.Tests/BaseTest.cs
test/Helsenorge.Messaging.Tests/Mocks/MockMessagingServer.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/AsynchronousReceiveTests.cs

Registries: Add PingAsync to Registry interfaces 
* This patch adds a PingAsync methods for the interfaces IAddressRegistry and ICollaborationProtocolRegistry.
* The ICollaborationProtocolRegistry.PingAsync method is currently a hack since that Web Service does not yet expose a Ping method.
MessagingException: Add two new Event Ids
- Added Event Ids:
- 38 - ConnectionToWebServiceFailed
- 39 - ConnectionToMessageBrokerFailed
MessagingServer: Verify our authentication credentials
- Before we start the Receive loop in the MessagingServer verify that we can authenticate against the external services using our credentials.
MessagingServer: Make MessagingServer mockable and add Mock
- We need to be able to mock out methods on MessagingServer. Therefore we
have removed the sealed keyword from …

Verify authentication credentials

---

Examples/PooledReceiver/Program.cs
Examples/PooledSender/Program.cs
src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Messaging/ServiceBus/LinkRole.cs
src/Helsenorge.Messaging/ServiceBus/MessageBrokerDialect.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusConnection.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusFactoryPool.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusReceiver.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusSender.cs
test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusFixture.cs
test/Helsenorge.Messaging.Tests/ServiceBus/ServiceBusConnectionTests.cs

This patch adds RabbitMQ dialect specifics for how to build Link Addresses.
For more information on Routing and Addressing in RabbitMQ, see:
https://github.com/rabbitmq/rabbitmq-server/tree/master/deps/rabbitmq_amqp1_0#routing-and-addressing

ServiceBus+Tests: Add support for RabbitMQ Routing+Addressing

---

src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Senders/AsynchronousSendTests.cs
test/Helsenorge.Registries.Tests/CertificateValidatorTests.cs

This patch makes sure that we serialize the SEID2.0 encryption
certificate we receive from CPPA Registry by identifying the correct
key usage flag.

Registries+Tests: Serialize SEID2.0 encryption certificates

---

Examples/Helsenorge.Messaging.Client/ClientSample.json
Examples/PooledReceiver/Program.cs
Examples/PooledSender/Program.cs
src/Helsenorge.Messaging/ApplicationPropertiesExtensions.cs
src/Helsenorge.Messaging/MessagingCore.cs
src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Messaging/ServiceBus/LinkFactory.cs
src/Helsenorge.Messaging/ServiceBus/LinkFactoryPool.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusFactory.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusFactoryPool.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusSender.cs
test/Helsenorge.Messaging.IntegrationTests/ServiceBus/ServiceBusFixture.cs

This adds the property MessagingSettings.ApplicationProperties which
lets users of the API to add custom Application Properties which will be
propogated to ServiceBusSender and applied to Amqp.Message before we
send the message.
This enables us to easily add additional required Amqp.Message
ApplicationProperties at a later stage.
This lets us enrich the MessagingSettings.ApplicationProperties with
additonal System Information, such as:
- Full name of Executing Assembly
- Version of Executing Assembly
- Target Framework the Entry Assembly is running under
- Host name of that host
This will be valuable information for Operations when troubleshooting
support issues for the clients.

ServiceBus+Core+Examples: Add MessagingSetting.ApplicationProperties and propogate to ServiceBusSender

---

src/Helsenorge.Registries/CollaborationProtocolRegistry.cs

When this exception gets logged, its very hard to understand what has happened. Especially when the person reading the log has no context for the warning.
This is an attempt to make the log message a bit less cryptic and allow the end user to debug what HerId fails, without having to log debug.

Update exception logging text in CollaborationProtocolRegistry

---

src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs

Adds a configuration option to enable warnings in the logs for
non-encrypted and non-signed payloads.
The configuration option defaults to true and is named
'LogMessagesNotSignedAndEnvelopedAsWarning'.

ServiceBus: Log warnings for non-encrypted and non-signed payloads

---

Examples/Helsenorge.Messaging.Client/Helsenorge.Messaging.Client.csproj
Examples/Helsenorge.Messaging.Server/Helsenorge.Messaging.Server.csproj
Examples/PooledReceiver/PooledReceiver.csproj
Examples/PooledSender/PooledSender.csproj
src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj

These dependencies are not needed for our libraries to build since there
are no direct dependencies on them.

deps: Remove non-necessary dependencies

---

src/Helsenorge.Messaging/ServiceBus/LinkFactory.cs
src/Helsenorge.Messaging/ServiceBus/LinkFactoryPool.cs

This makes sure we that instantiate _applicationProperties in LinkFactory and LinkFactoryPool.

ServiceBus: Make sure that _applicationProperties is always instantiated 

---

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Receivers/SynchronousReceiveTests.cs

Do not send an error message to the external senders error queue when the Send operation fails.

ServiceBus: Do not send an error message when Send operation fails

---

src/Helsenorge.Messaging/Abstractions/ICachedMessagingEntity.cs

commit 0a9526a798884a7dc40830d1d8621ba5a41004d1 implemented async on Close so this line of the comment appears to be outdated.

Remove outdated comment in

---

src/Helsenorge.Messaging/ServiceBus/AmqpErrorExtensions.cs

Fixes #353 
Also include two additional commits:
- ServiceBus: Only produce string from StringBuilder when string is needed
- ServiceBus: Remove unnecessary braces

ServiceBus: Do not use AppendFormat for non-formatted strings

---

src/Helsenorge.Registries/ServiceBusManager.cs

Mistakenly passing systemIdent to eventName and vice versa.

ServiceBusManager: Re-order argument sequence for SubscribeAsync

---

src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs

When serializing X509 certificates, using `.Export(X509ContentType.SerializedCert)` causes an exception in Linux:
> System.PlatformNotSupportedException: X509ContentType.SerializedCert and X509ContentType.SerializedStore are not supported on Unix
`X509ContentType.SerializedCert` causes the cert library to use Windows native functions to serialize the certificate, presumably to preserve encoded properties in Windows Certificate Store. If only the public key is required, this shouldn't be necessary, and `X509ContentType.Cert` can be used instead.
More information: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509contenttype?view=net-6.0

Registries: Cert serialization working on linux

---

src/Helsenorge.Messaging/MessagingServer.cs

This removes the pre-authentication steps because we have had issues
with the step failing in test and production environments unrelated to
authentication.
Closes #378

MessagingServer: Remove pre-authentication step against SOAP services

---

src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs

This property indicates if this message has been aquired before, or if this is the first time it is aquired.

ServiceBus: Add property FirstAquirer

---

src/Helsenorge.Registries/AddressRegistry.cs
test/Helsenorge.Registries.Tests/AddressRegistryTests.cs

The responses from the AddressRegistry SOAP requests are cached rather than their abstracted counterparts used in the calling code. Because of this, information that is never used is put into the cache. In one case, this also causes problems with the recently added `XmlCacheFormatter` formatter, because `DataContractSerializer` doesn't understand how to deserialize the objects.
The proposed solution is to map the responses before adding them to the cache. This breaks existing cache records, so the change cannot be done universally within a minor release. Because of this, the change will only affect setups using the `XmlCacheFormatter` for now.

Registries: Cache mapped instead of SOAP AR values

---

src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs

This fixes a bug where we would set the queue name of the receiver as our ReplyTo value.

ServiceBus: Set correct ReplyTo value

---

src/Helsenorge.Registries/Abstractions/CollaborationProtocolMessage.cs
src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs

ThisPartyActionBinding:action maps to new property CollaborationProtocolMessage.Action.
CollaborationProtocolMessage.Name is now mapped from ProcessSpecification:name.
These changes are backward compatible.
This commit fixes the issue #395

Registries: Mapping changes for abstractions

---

src/Helsenorge.Messaging/MessagingClient.cs

This is a fix to add the DeliveryChannel for the scenario where the external party is missing the communication process DIALOG_INNBYGGER_TIMERESERVASJON.

Messaging: Add DeliveryChannel to Dummy Collaboration Protocol Agreement

---

src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs

This adds an asynchronous DeliveryChannel to the Dummy instance of our CollaborationProtocolProfile.

Registries: Add DeliveryChannel to DummyCollaborationProtocolProfile

---

src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs

This patch avoids a NullReferenceException in FindMessageForReceiver() and FindMessageForSender().

Registries: Make sure we null-check ProcessSpecification

---

src/Helsenorge.Registries/Abstractions/ProcessSpecification.cs

Avoid parsing VersionString if it's null, empty or only consists of whitespace.

Registries: Do not parse VersionString if it's null or empty

---

src/Helsenorge.Messaging/ServiceBus/Senders/SynchronousSender.cs

Instead of 0 log our own HER-id.

ServiceBus: Add our own HER-id to the ResponseTime log statement

---

src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs
test/Helsenorge.Messaging.Tests/ServiceBus/ServiceBusMessageTests.cs

Copying reference types from the original message causes hard to find bugs when we start to manipulate the values of these references.
For example: in SendError() before we send a reply to the recipients error queue we:
1. clone the message
2. Switch ServiceBusMessage.FromHerId and ServiceBusMessage.ToHerId on the cloned message
3. The result we end up with is ToHerId and FromHerId both have the same HER-id
4. In addition we have manipulated the values of both originalMessage and clonedMessage since in the underlying object these are stored in a Dictionary/Map which is a reference type.
In-house reference: [283463](https://dev.azure.com/nhnfelles/Helsenorge/_workitems/edit/283463)
Supersedes #414

ServiceBus: Do not copy reference types from original message in Clone()

---

.github/workflows/build.yml
.github/workflows/nuget-deploy.yml
Examples/RepublishExample/Program.cs
Examples/RepublishExample/RepublishExample.csproj
Messaging.sln
src/Helsenorge.Messaging.AdminLib/ConnectionString.cs
src/Helsenorge.Messaging.AdminLib/HeaderNotOfExpectedTypeException.cs
src/Helsenorge.Messaging.AdminLib/Helsenorge.Messaging.AdminLib.csproj
src/Helsenorge.Messaging.AdminLib/MissingHeaderException.cs
src/Helsenorge.Messaging.AdminLib/QueueClient.cs
src/Helsenorge.Messaging.AdminLib/QueueUtilities.cs
src/Helsenorge.Messaging.AdminLib/RabbitMQ/QueueClient.cs
src/Helsenorge.Messaging.AdminLib/SourceAndDestinationIdenticalException.cs
src/Helsenorge.Messaging/ServiceBus/QueueType.cs
test/Helsenorge.Messaging.AdminLib.Tests/Helsenorge.Messaging.AdminLib.Tests.csproj
test/Helsenorge.Messaging.AdminLib.Tests/QueueClientTests.cs

This adds Helsenorge.Messaging.AdminLib consisting of a QueueClient with the methods:
- GetMessageCount()
- RepublishMessagesFromDeadLetter()
- MoveMessages()
Currently the library is simplified. It will be expanded based on needs from the ServiceBus migration project.

AdminLib+Examples+Tests: Add Helsenorge.Messaging.AdminLib

---

src/Helsenorge.Messaging/MessagingClient.cs

This adds CPA or CPP Id to the exception message. Only one of the identificators will be available, but we use the same abstraction regardless of it being a CPA or CPP.

Messaging: Add CPA/CPP Id when throwing Invalid delivery protcol

---

src/Helsenorge.Messaging/ServiceBus/ServiceBusReceiver.cs

This patch removes the EnsureOpen{,Async} calls before doing an operation on the AMQP message.
If we recreate the link before executing operations on the already retrieved message we will just get an exception telling us that the message is not associated with the link, so no point trying to recreate the link at this point.

Messaging: Don't call EnsureOpen before doing operations on AMQP message

---

src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs

When disposing or stopping MessageServer cancellationtoken was cancelled, this give exception in the Task.Delay and the Shutdown of the Sender- Receiver- and FactoryPool never got called.
People calling Stop or Dispose when the windows-service was stopped/restarted do not notice this bug since all connections are closed when the MessageServer is destroyed.
For those who call dispose on MessageServer and then construct a new MessageServer and Start the new one, will get connectionsleak "hanging in there" for ever.
Thanks to @sandisa doing great research for this bug

not throwing taskcanceledexception when token i cancelled

---

src/Helsenorge.Messaging/Abstractions/IMessagingMessage.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs
test/Helsenorge.Messaging.Tests/Mocks/MockMessage.cs

This exposes the GroupId AMQP property on IMessagingMessage.
This property is used by Iplos messages to split large file into
smaller files.

Messaging: Expose GroupId on IMessagingMessage 

---

src/Helsenorge.Messaging/MessagingClient.cs
src/Helsenorge.Messaging/MessagingSettings.cs
src/Helsenorge.Messaging/ServiceBus/Receivers/MessageListener.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
src/Helsenorge.Registries/DummyCollaborationProtocolProfileFactory.cs
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs
test/Helsenorge.Registries.Tests/Files/CommunicationDetails_93238.xml

This PR add suppport for sending/receiving messages without CPA resolve.
By adding message functions to MessageFunctionsExcludedFromCpaResolve list in MessagingSettings, CPA resolve will be skipped for those message functions. An dummy CPA will be used instead.
This will make it possible to use Helsenorge.Messaging for communication with both Helsenorge and other communication parties not using CPA.

Registries+Messaging: Add support for skipping CPA resolve

---

src/Helsenorge.Registries/Abstractions/CollaborationProtocolMessage.cs
src/Helsenorge.Registries/Abstractions/CollaborationProtocolProfile.cs
src/Helsenorge.Registries/Abstractions/CollaborationProtocolRole.cs
src/Helsenorge.Registries/CollaborationProtocolRegistry.cs
src/Helsenorge.Registries/Utilities/StringExtensions.cs

This moves the helper methods in `CollaborationProtocolRegistry` out into `CollaborationProtocol{Message,Profile,Role}` and  rebrands them as factory methods.

Registries: Add factory methods for CollaborationProtocol{Message,Profile,Role}

---

src/Helsenorge.Messaging/ServiceBus/ServiceBusMessage.cs

Cloning the user_id property on a message sent to us by another user will cause RabbitMQ to reject the message.

Messaging: Do not include the user_id property when cloning message

---

src/Helsenorge.Messaging/MessagingClient.cs
src/Helsenorge.Messaging/ServiceBus/ServiceBusCore.cs
src/Helsenorge.Registries/DummyCollaborationProtocolProfileFactory.cs
test/Helsenorge.Messaging.Tests/BaseTest.cs
test/Helsenorge.Messaging.Tests/ServiceBus/Senders/AsynchronousSendTestsWithoutCpp.cs
test/Helsenorge.Registries.Tests/CollaborationRegistryTests.cs

Sending APPREC for message functions without CPP/CPA resulted in an error even though the message function was listed in config variable MessageFunctionsExcludedFromCpaResolve. This PR fixes that issue.

Messaging+Registries: Fix message function exceptions for apprec

---

Documentation/MigrateFrom4To5.md
Examples/PooledReceiver/Program.cs
Examples/PooledSender/Program.cs
Examples/SubscriptionExample/Program.cs
src/Helsenorge.Messaging/MessagingSettings.cs
test/Helsenorge.Messaging.Tests/BaseTest.cs

This reverts us back to using string as data type for the configuration
setting MessagingSettings.ConnectionString.

Messaging: Revert to using string as data type for MessagingSettings.ConnectionString

---

src/Helsenorge.Messaging/Abstractions/IMessageProtection.cs
src/Helsenorge.Messaging/Abstractions/MessageProtection.cs
src/Helsenorge.Messaging/Security/NoMessageProtection.cs
src/Helsenorge.Messaging/Security/SignThenEncryptMessageProtection.cs
test/Helsenorge.Messaging.Tests/Amqp/Receivers/AsynchronousReceiveTests.cs

This adds the overload `Protect(Stream, X509Certificate2, X509Certificate2)` to `IMessageProtection`.

Messaging: Add Protect overload to IMessageProtection

---

src/Helsenorge.Messaging/Amqp/AmqpSender.cs
src/Helsenorge.Messaging/ApplicationPropertiesExtensions.cs

This patch checks if the map already contains a key with name 'enqueuedTimeUtc'. If it exists update the value, if not add it.
https://norskhelsenett.slack.com/archives/C03HKUXDTT6/p1679403558780279

Messaging: Check if Map already contains 'enqueuedTimeUtc'

---

src/Helsenorge.Messaging/Amqp/LinkFactory.cs
src/Helsenorge.Messaging/Amqp/LinkFactoryPool.cs

This transfer MessageFunction from OutgoingMessage to AmqpMessage the same way we do in MessagingClient, always transferring MessageFunction, not ReceiptForMessageFunction.

Messaging: Always use MessageFunction not ReceiptForMessageFunction

---

src/Helsenorge.Registries/Abstractions/CertificateDetails.cs
test/Helsenorge.Registries.Tests/AddressRegistryTests.cs

This marks the class `CertificateDetails` as `Serializable` and manually serializes/deserializes the certificate to/from a base64 string.

Registries: Manually {de,}serialize CertificateDetails.Certificate

---

src/Helsenorge.Registries/Helsenorge.Registries.csproj

This updates System.ServiceModel.* to 4.10.2 for netstandard2.0 and 6.0.0 for net6.0.

deps: Update System.ServiceModel.* to 4.10.2 and 6.0.0

---

src/Helsenorge.Registries/Utilities/CacheExtensions.cs

This removes warning: "Missing XML comment for publicly visible type or member 'CacheExtensions'".

Registries: Add XML comment to publicy visible type CacheExtensions

---

Documentation/OppdaterProxyKlasser.md
src/Helsenorge.Registries/Connected Services/ServiceBusManagerServiceV2/ServiceBusManagerServiceV2.cs

This disables the warning CS1591 in the auto-generated file ServiceBusManagerServiceV2.cs.

Registries: Disable warning CS1591 in ServiceBusManagerServiceV2.cs

---

Examples/ReceiveDecryptAndValidate/Program.cs
Examples/SignEncryptAndSend/Program.cs
src/Helsenorge.Messaging/MessagingClient.cs
src/Helsenorge.Messaging/MessagingCore.cs
src/Helsenorge.Messaging/MessagingServer.cs
src/Helsenorge.Messaging/Security/SignThenEncryptMessageProtection.cs
test/Helsenorge.Messaging.Tests/Amqp/Receivers/AsynchronousReceiveTests.cs
test/Helsenorge.Messaging.Tests/Security/SignThenEncryptMessageProtectionTests.cs

This is gonna be used for statistics on what encryption types are being used. Will also be used to name and shame software that is using encryption algorithms that are past the EoL

Log out what encryption algorithm is being used when unprotecting

---

Examples/Helsenorge.Messaging.Client/Helsenorge.Messaging.Client.csproj
Examples/Helsenorge.Messaging.Server/Helsenorge.Messaging.Server.csproj
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Messaging.AdminLib.Tests/Helsenorge.Messaging.AdminLib.Tests.csproj
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj
test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj

.NET Core 3.1 target is EOL and can safely be removed. See individual commits for more details.

Meta+deps: Remove the netcoreapp3.1 target and bump various dependencies

---

test/Helsenorge.Messaging.Tests/Amqp/Exceptions/BusOperationTests.cs
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj

We did no really use Moq for much, and we had our own Mocking Provider for creating loggers so let's use that one.

Tests: Remove our dependency on Moq

---

src/Helsenorge.Registries/Utilities/SoapServiceInvoker.cs

This adds comments to clarify that we intentionally try to avoid locking the first time we try to retrieve the ChannelFactory from the cache, and also why we after locking try to retrieve the ChannelFactory again.
Also refactors the code a bit to avoid unnecessary indentation/nesting.

Registries: Clarify why we avoid locking when retrieving ChannelFactory

---

src/Helsenorge.Messaging/Amqp/AmqpCore.cs
src/Helsenorge.Messaging/Amqp/MetadataHelper.cs
src/Helsenorge.Messaging/Amqp/MetadataKeys.cs
src/Helsenorge.Messaging/MessagingSettings.cs
test/Helsenorge.Messaging.Tests/Amqp/MetadataHelperTests.cs
test/Helsenorge.Messaging.Tests/Amqp/Senders/AsynchronousSendTests.cs
test/Helsenorge.Messaging.Tests/Files/MetadataTestsDialogmelding11.xml
test/Helsenorge.Messaging.Tests/Files/MetadataTests_Apprec10.xml
test/Helsenorge.Messaging.Tests/Files/MetadataTests_Apprec11.xml
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj

Feature added to improve auditing and tracing
Important none-sensitive properties are extracted from the payload and added as amqp application properties.
This makes tracing MessageIds alot easier and also open for correlation between businessdocument and application receipt

Extracting data from payload and adding them as amqp properties

---

src/Helsenorge.Messaging/Amqp/MetadataHelper.cs

If element is null it is a bug in the business logic calling this module but validating it is not part of this code's responsiblity

Do not throw exception if XElement is null/empty

---

.github/workflows/build.yml

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

workflows: Add MacOS M1 Runner

---

.github/workflows/build.yml
.github/workflows/nuget-deploy.yml
Examples/Helsenorge.Messaging.Client/Helsenorge.Messaging.Client.csproj
Examples/Helsenorge.Messaging.Server/Helsenorge.Messaging.Server.csproj
Examples/PooledReceiver/PooledReceiver.csproj
Examples/PooledSender/PooledSender.csproj
Examples/ReceiveDecryptAndValidate/ReceiveDecryptAndValidate.csproj
Examples/RepublishExample/RepublishExample.csproj
Examples/SearchByIdAndGetOrganizationDetailsExample/SearchByIdAndGetOrganizationDetailsExample.csproj
Examples/SignEncryptAndSend/SignEncryptAndSend.csproj
Examples/SimpleReceiver/SimpleReceiver.csproj
Examples/SimpleSender/SimpleSender.csproj
Examples/SubscriptionExample/SubscriptionExample.csproj
src/Helsenorge.Messaging.AdminLib/Helsenorge.Messaging.AdminLib.csproj
src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Messaging.AdminLib.Tests/Helsenorge.Messaging.AdminLib.Tests.csproj
test/Helsenorge.Messaging.Tests.Mocks/Helsenorge.Messaging.Tests.Mocks.csproj
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj
test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj

We now explicitly target the following .NET targets:
- netstandard2.0
- This means we are compatible with .NET Framework 4.6.2 and newer targets, including .NET Core targets + .NET 5, 6, and 8. There are some compatibility issues with SOAP support across the various targets, therefore we have to keep the netstandard2.0 target for now. This could be investigated further later
- net6.0
- This target will be removed in the future when LTS ends.
- net8.0

Everywhere: Add .NET 8 target framework

---

src/Helsenorge.Registries/CertificateValidator.cs

Nothing was done with the contents of the StringBuilder so this can be safely removed.

Messaging: Remove unused StringBuilder

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/nuget-deploy.yml
src/Helsenorge.Messaging.AdminLib/Helsenorge.Messaging.AdminLib.csproj
src/Helsenorge.Messaging/Amqp/Receivers/HeaderValidationException.cs
src/Helsenorge.Messaging/Amqp/Receivers/ReceivedDataMismatchException.cs
src/Helsenorge.Messaging/Amqp/Receivers/UnsupportedMessageException.cs
src/Helsenorge.Messaging/Amqp/ReportableErrorException.cs
src/Helsenorge.Messaging/Helsenorge.Messaging.csproj
src/Helsenorge.Registries/Helsenorge.Registries.csproj
test/Helsenorge.Messaging.AdminLib.Tests/Helsenorge.Messaging.AdminLib.Tests.csproj
test/Helsenorge.Messaging.Tests.Mocks/Helsenorge.Messaging.Tests.Mocks.csproj
test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj
test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj

We still have the targets for netstandard2.0 (net462), net6.0, net8.0.

Messaging: Add net9.0 target + remove legacy serialization support ctor

---

Directory.build.props
src/Helsenorge.Messaging/Amqp/CachedAmpqSessionEntity.cs

Sending messages occasionally reports "The operation close did not complete within the allocated time 60000 for object Session" and sending the message (async or sync) is delayed for 60s which gives timeouts in calling services. This fix reduses the timeout to give sending the message time to complete within reasonable timeouts

Default close timeout is 60s which delays message sending

---

src/Helsenorge.Registries/Connected Services/HelseId/HelseIdClient.cs
src/Helsenorge.Registries/Helsenorge.Registries.csproj
src/Helsenorge.Registries/Utilities/RestServiceInvoker.cs

Moves us from the now deprecated library IdenityModel to Duende.IdentiyModel. These libraries are identitcal and is more of a namespace change than anything else.

Registries: Move from IdentityModel to Duende.IdentityModel
